BUG: The day calculation is wrong ever after overflow fix
```let (mut day, day_fraction) =
        quorem(month_fraction, SECONDS_PER_DAY * days_this_month as
f64);```
>>> 172800 / 2678400.
0.06451612903225806
>>> 172800 % 2678400
172800
Location:
year_fraction = 172800 || month_fraction = 172800 || day_fraction =
172800 ||
            secs this month = 2678400
fixed hours from 48 to 24
172800 => 1970 1 2 T 24 0 0
172800 => 1970 1 2 T 24 0 0 [u8]
thread 'utc_valid_dates' panicked at 'assertion failed: `(left ==
right)`
  left: `Utc { year: 1970, month: 1, day: 3, hour: 0, minute: 0, second:
0, nanos: 0 }`,
 right: `Utc { year: 1970, month: 1, day: 2, hour: 24, minute: 0,
second: 0, nanos: 0 }`: Conversion from instant failed + 0 0 0',
tests/utc.rs:31:20

This is effectively seconds, but don't I expect just days?